### ISSUE TITLE
Update pypi to include MediaCling

### ISSUE THREAD

**Issue by derek73** [kennethreitz/dj-static#16]
Version 0.0.5 that is currently on pypi does not include the MediaCling class. This means you cannot follow the read me instructions on github using `pip install dj-static` and get the results shown. Instead you get: 

```
ImportError: cannot import name MediaCling
```

Just a friendly reminder to update pypi. It looks like hundreds of people download this project from pypi each day.

https://pypi.python.org/pypi/dj-static/0.0.5

The workaround is to install from github directly.

```
pip install -e git+git://github.com/kennethreitz/dj-static.git#egg=dj-static
```

**Comment by flevour** [comment]
This can be closed.
