### ISSUE TITLE
Allow specifying subclass of `static.Cling` to use when creating `dj_static.cling`

### ISSUE THREAD

**Issue by cool-RR** [kennethreitz/dj-static#27]

**Comment by flevour** [comment]
Could you elaborate a bit further?

**Comment by cool-RR** [comment]
There's this line in `Cling.__init__`:

        self.cling = static.Cling(base_dir)

I wish instead of being hardcoded to `static.Cling` there would be an option to specify a subclass of `static.Cling`. I currently do this in a roundabout way because dj-static doesn't provide an option for this.
