### ISSUE TITLE
Error when deploying to Heroku

### ISSUE THREAD

**Issue by jcpmmx** [kennethreitz/dj-static#28]
I was having this error when trying to deploy a Django app to Heroku (following their tutorial). This also happens when running ```foreman start``` locally.

```
ImproperlyConfigured: Requested setting USE_I18N, but settings are not configured.
You must either define the environment variable DJANGO_SETTINGS_MODULE or call
settings.configure() before accessing settings.
```

The solution?
Setting the ```DJANGO_SETTINGS_MODULE``` *before* importing and calling Cling.

```
import os
from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'trappt.settings')

from dj_static import Cling
application = Cling(get_wsgi_application())
```

**Comment by flevour** [comment]
This can be closed.

**Comment by ryneeverett** [comment]
Why was this closed? Shouldn't it at least be documented in the README?

**Comment by kennethreitz** [comment]
Why would `DJANGO_SETTINGS_MODULE` not be set? How are you launching Django?

**Comment by jcpmmx** [comment]
Not sure right now TBH.
But I remember debugging that and getting the error, and solving it by having `DJANGO_SETTINGS_MODULE` move up before Cling.

**Comment by ryneeverett** [comment]
> Why would `DJANGO_SETTINGS_MODULE` not be set?

It wouldn't be set unless you set the environmental variable. Often this is unnecessary which is why the default wsgi.py created by `python manage.py startproject` sets a default:

```py
"""
WSGI config for mysite project.

It exposes the WSGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/howto/deployment/wsgi/
"""

import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "mysite.settings")

application = get_wsgi_application()
```
